Add RAII for passing through get time ops.
replayio/gecko-dev pull request #768
Opened 2022-03-23 21:35 UTC by kannanvijayan

The initial purpose of this for use within various
AutoProfilerTextMarker events that are triggering
mismatches on calls to clock_gettime.

The intuition is that there are places where reasonable
non-determinism during replay might spuriously cause
mismatches due to heading down irrelevant profiler codepaths,
which shouldn't matter for our purposes.

2022-03-23 21:36 UTC, kannanvijayan commented
See issue https://github.com/RecordReplay/backend/issues/4881

2022-03-23 22:03 UTC, jasonLaster commented
@kannanvijayan out of curiosity, how are you testing this?

2022-03-23 22:59 UTC, kannanvijayan commented
> @kannanvijayan out of curiosity, how are you testing this?

This patch itself doesn't do much except set up the RAII wrapper.  After I land it I want to use it in various places, starting with `AutoProfilerTextMarker`.

I don't have a clear testing plan for those subsequent changes aside from manually smoketesting it and looking for an obvious crash.

All of the auto profiler stuff tends to interact with subsystems that really shouldn't matter to page execution.  That's the guess anyway.

Maybe Brian has better ideas for testing.  I'll ask for review after I confirm it builds :)

2022-03-24 01:11 UTC, kannanvijayan commented
@bhackett1024 I mostly cribbed this implementation, but I have a couple of questions.

1. Where's the actual thing that sets a thread-local flag?  I suspect it's tucked away under one of those macro invocations somewhere but I don't know specifically.
2. I'll then need to hook into this from the _backend_ driver and linker implementation for various time-getter API functions, and conditionalize them on the pass-through flag.  But I'm a bit confused about how I'd get at that from the driver/linker code when all of this stuff lives in gecko-land.

2022-03-24 13:46 UTC, bhackett1024 commented
> @bhackett1024 I mostly cribbed this implementation, but I have a couple of questions.
> 
>     1. Where's the actual thing that sets a thread-local flag?  I suspect it's tucked away under one of those macro invocations somewhere but I don't know specifically.
> 
>     2. I'll then need to hook into this from the _backend_ driver and linker implementation for various time-getter API functions, and conditionalize them on the pass-through flag.  But I'm a bit confused about how I'd get at that from the driver/linker code when all of this stuff lives in gecko-land.

The thread-local flags for whether events are passed through / disallowed are in the recorder (aka the driver) and the linker used when replaying.  They are set / cleared using the APIs the recorder exports (the ones being called in ProcessRecordReplay.cpp), which makes them easy to check from within the recorder.

2022-03-24 13:50 UTC, bhackett1024 requested changes
I can't review this without seeing the places where you're actually planning on using this class.  I strongly feel that any places where this would be needed would be better suited to using the existing AutoPassThroughThreadEvents class in the appropriate way.

We don't want to pass through time operations in large swaths of gecko without also passing through other operations, because most places in gecko we want the time operations to use whatever value was available when recording, or else it will start behaving differently.  In order to pass through time operations in a specific place, we can just use AutoPassThroughThreadEvents.

2022-03-24 14:53 UTC, kannanvijayan commented
The most obvious place where I wanted to use this was within the various profiler-related RAII helpers, which incidentally take the current time.

Another example is a situation we ended up fixing using a different approach (skipping observer hooks for major GC), but where once again the mismatch was caused by the use of a profiler marker within the callback invocation code.

I wasn't aware that AutoPassThroughThreadEvents suppressed all interaction with the recording stream.  I figured it was specifically related to actual page events and browser event loop only.

2022-03-24 14:58 UTC, bhackett1024 commented
I think AutoPassThroughThreadEvents would work for these cases.  These mark regions where, yeah, execution should not interact with the recording stream at all --- calls will not be added to the recording, and when replaying they won't read data from the recording and will try to perform them without any recording interaction.  The precise semantics of these have not been well defined or documented, unfortunately, fixing that will be part of https://github.com/RecordReplay/backend/issues/3195

2022-03-25 16:49 UTC, kannanvijayan commented
Cool, thanks for the feedback.  I'll abandon this approach and use AutoPassThroughThreadEvents.

2022-03-25 16:49 UTC, closed without merging